from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain

def respond(query, retriever):
    """
    A function that retrieves the 5 most relevant docs from a retiever object and uses them to answer the query.
    
    query: (str) The input query in natural language.
    retriever: (langchain.vectorstores.base.VectorStoreRetriever) The retriever object to query for relevant docs.
    
    returns: (dict) a dictionary object containing the response generated by the LLM.
    """
    docs = retriever.get_relevant_documents(query)[:5]
    chain = load_qa_chain(OpenAI(temperature=0.2), chain_type="stuff")
    response = chain({"input_documents": docs, "question": query}, return_only_outputs=True)
    return response